spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supermarket?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  #上传文件配置
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 200MB

# Server settings (ServerProperties)
server:
  port: 8888
  servlet:
    context-path: /supermarket

log:
  level: INFO
  #  path: C:/logs/supermarket
  path: D:/logs/supermarket

cors:
  allowedOrigins: 'http://127.0.0.1:8088'

upload:
  path: D:/upload/images/
  url: http://127.0.0.1:8001/